
= JDG Remote Cache as a Data Source


== Use Case

This use case is to access a JDG remote cache, via Hot Rod Client, as a data source and to expose the data thru JDV and joined with other federated data sources.   The JDG cache can be an existing cache or a new cache.

== For Each JDG Cache that will be Accessed

The following is the process for integrating a JDG remote cache as a data source in JDV.   This should be done for each JDG Cache that will be accessed, even when sharing the same cache.  See link:Limitations.adoc[Limitations]


===  In the JDG Server

*  a cache needs to be configured, or is already available
*  start JDG server

===  Create Pojo

see link:PojoConfiguration.adoc[Pojo Creation] regarding how to create the pojo jar that will be used by the resource-adapter to configure the JDG schema.


===  JDV Server Configuration

*  deploy pojo module that was created
*  if using pojo annotations, edit the module.xml for org.jboss.teiid.resource-adapter.infinispan.dsl resource adapter to add the pojo module dependency

[source]
.*Example module dependency*
----
<module name="{your.pojo.module.name}"  optional="true"  export="true" />
----

*  restart server

=== Configuring JDG Resource Adapter

See https://teiid.gitbooks.io/documents/content/v/9.1.x/admin/Infinispan_HotRod_Data_Sources.html[Infinispan DSL (Hot Rod) DataSources] for all the properties that could be used to configure the JDG resource adapter and will be covered in the following.

==== A. Use JBDS / Teiid Designer Tooling

Use link:JDG_Connection_Profile.adoc[Teiid Designer JDG Connection Profile] tooling to create the data source.

==== B. Use CLI script
 
For example CLI scripts for installing resource adapter, see /docs/teiid/datasources/infinispan in the JDV server.


==  VDB Creation


=== Create VDB xml (Dynamic)

A quick way to expose the JDG data source is to deploy a VDB xml file where the metadata will be exposed by reverse engineering from the defined pojo's on the resource adapter.  See the link:Examples_VDB_Simple.adoc[VDB Example].

=== Create VDB using Teiid Desginer

The following will explain the steps to Teiid Designer to model the JDG Source and build a VDB to access the JDG cache.

.  Perform the above steps to deploy the pojo and configure the resource adapter
.  You have Teiid Designer open with a model project created or opened, and connected to the JDV server
.  Use link:Teiid_Connection_Importer.adoc[Teiid Connection Importer] to create the source model from the JDG Data Source.
.  Create the VDB that contains the source model.
.  Deploy and Test.


