
= Pojo Creation

This will discuss the options for creating a pojo for deployment as a module to the JDV server.

NOTE:  Using complex data types, see link:Limitations.adoc[Limitations using Protobuf] .

WARNING:  Any time the pojo is changed, like adding/removing method or changing data types, the JDG cache will have to be reloaded because the JDG schema is being changed.


== 1. How will JDG Schema be Configured in Hot Rod Client

The following is to help you determine how to create the pojo and related artifacts.

[cols="2,6"]
|===
|*Installed JDG Version* 
|*Configure Schema Options*

|6.4 or 6.5
|use pojo, protobuf (.proto) defintion file and marshallers

|6.6+
|use pojo, protobuf (.proto) defintion file and marshallers or use pojo containing protobuf annotations

|===

*  If using pojo, protobuf (.proto) defintion file and marshallers will need to use the options JDG / Google provides for creating, see https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.6/html/Infinispan_Query_Guide/sect-Protobuf_Encoding.html[Infinispan Query Guide to Protobuf Encoding]
*  If using pojo containing protobuf annotations see https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.6/html/Infinispan_Query_Guide/sect-Protobuf_Encoding.html#Defining_Protocol_Buffers_Schemas_With_Java_Annotations[Define Schemas with Java Annotations]


== 2. Create Pojo


=== Using Teiid Designer

There are 2 ways to create the pojo:

*  Select view/table then right mouse click, select Modeling --> Create Pojo
*  Select view then right mouse click, select Materialize (this wizard will provide the option to create the pojo)

The result of these options can be a packaged module zip that can be used to deploy the pojo to the JDV server by unzipping at the JBOSS_HOME root directory.

=== Manually Creating Pojo

*  If using pojo, protobuf (.proto) defintion file and marshallers will need to use the options JDG / Google provides for creating, see https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.6/html/Infinispan_Query_Guide/sect-Protobuf_Encoding.html[Infinispan Query Guide to Protobuf Encoding]
* If creating pojo that contains protobuf annotations see https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.6/html/Infinispan_Query_Guide/sect-Protobuf_Encoding.html#Defining_Protocol_Buffers_Schemas_With_Java_Annotations[Define Schemas with Java Annotations]

When manually creating the pojo, will also need to deploy it as a module to the JDV server.   The following is an example of the pojo module that should be used:

[source,xml]
.*Sample module.xml file*
----
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="${module-name}">
    <resources>
        <resource-root path="{your-pojojarname}" />
    </resources>

    <dependencies>
        <module name="org.infinispan.client.hotrod" slot="${jdg.slot}" optional="true" services="export"/>
   	<module name="org.infinispan.protostream" slot="${jdg.slot}"  optional="true" services="export"/>

        <module name="org.jboss.teiid.resource-adapter.infinispan.dsl" export="true" />
    </dependencies>
</module>
----

Where:::
* ${module-name} is replaced with the folder structure of module.  Example:   folder - com/client/my/pojo/  then module-name is  com.client.my.pojo
* ${your-pojojarname} is replaced with the name of jar where the pojo is packaged.  Example:  pojo.jar
* The ${jdg.slot} needs to be substituted with the slot associated with the JDG Hot Rod Client EAP module kit installed.  Example:  jdg-6.6

NOTE: The ${module-name} will be needed when configuring the resource-adapter.

